package de.tasticgames.lobby.hud;

import javax.imageio.ImageIO;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Objects;
import java.util.logging.Logger;

/**
 * Exports the ItemsAdder content the HUD needs (dark rounded box glyphs + transparent boss bar
 * textures) into {@code plugins/ItemsAdder/contents/tasticgames}. Existing files are never
 * overwritten; after the first export the operator runs {@code /iazip} once.
 */
public final class HudAssetExporter {

    public static final int BOX_HEIGHT = 14;
    public static final int CAP_WIDTH = 4;
    public static final int MID_WIDTH = 8;

    private final File itemsAdderFolder;
    private final Logger logger;

    public HudAssetExporter(File itemsAdderFolder, Logger logger) {
        this.itemsAdderFolder = Objects.requireNonNull(itemsAdderFolder);
        this.logger = Objects.requireNonNull(logger);
    }

    /** @return the list of files that were created (empty when everything already existed) */
    public List<File> export(String bossbarColor) throws IOException {
        File contents = new File(itemsAdderFolder, "contents" + File.separator + "tasticgames");
        File configs = new File(contents, "configs");
        // ItemsAdder 3.x resolves font_image paths below contents/<pack>/textures/, 4.x below resourcepack/assets/<ns>/textures/ – write both
        File texturesLegacy = new File(contents, "textures" + File.separator + "hud");
        File textures = new File(contents, "resourcepack" + File.separator + "assets" + File.separator + "tasticgames" + File.separator + "textures" + File.separator + "hud");
        File bossBar = new File(contents, "resourcepack" + File.separator + "assets" + File.separator + "minecraft" + File.separator + "textures"
                + File.separator + "gui" + File.separator + "sprites" + File.separator + "boss_bar");
        File fonts = new File(contents, "resourcepack" + File.separator + "assets" + File.separator + PixelOffsets.NAMESPACE + File.separator + "font");
        Files.createDirectories(fonts.toPath());
        Files.createDirectories(configs.toPath());
        Files.createDirectories(texturesLegacy.toPath());
        Files.createDirectories(textures.toPath());
        Files.createDirectories(bossBar.toPath());
        List<File> created = new ArrayList<>();

        File config = new File(configs, "tasticgames_hud.yml");
        if (!config.exists()) {
            String yaml = """
                    # Generated by TasticLobby – HUD box glyphs (dark rounded background behind HUD cells).
                    info:
                      namespace: tasticgames
                    font_images:
                      hud_box_left:
                        path: hud/box_left.png
                        scale_ratio: %d
                        y_position: 11
                        show_in_gui: false
                      hud_box_mid:
                        path: hud/box_mid.png
                        scale_ratio: %d
                        y_position: 11
                        show_in_gui: false
                      hud_box_right:
                        path: hud/box_right.png
                        scale_ratio: %d
                        y_position: 11
                        show_in_gui: false
                    """.formatted(BOX_HEIGHT, BOX_HEIGHT, BOX_HEIGHT);
            Files.writeString(config.toPath(), yaml, StandardCharsets.UTF_8);
            created.add(config);
        }
        for (File folder : List.of(texturesLegacy, textures)) {
            created.addAll(writeBox(new File(folder, "box_left.png"), CAP_WIDTH, true, false));
            created.addAll(writeBox(new File(folder, "box_mid.png"), MID_WIDTH, false, false));
            created.addAll(writeBox(new File(folder, "box_right.png"), CAP_WIDTH, false, true));
        }

        File spaceFont = new File(fonts, PixelOffsets.FONT_NAME + ".json");
        if (!spaceFont.exists()) {
            Files.writeString(spaceFont.toPath(), PixelOffsets.fontJson(), StandardCharsets.UTF_8);
            created.add(spaceFont);
        }

        String color = bossbarColor.toLowerCase(Locale.ROOT);
        for (String name : List.of(color + "_background.png", color + "_progress.png")) {
            File file = new File(bossBar, name);
            if (!file.exists()) {
                BufferedImage transparent = new BufferedImage(182, 5, BufferedImage.TYPE_INT_ARGB);
                ImageIO.write(transparent, "png", file);
                created.add(file);
            }
        }
        for (String notch : List.of("6", "10", "12", "20")) {
            for (String kind : List.of("background", "progress")) {
                File file = new File(bossBar, "notched_" + notch + "_" + kind + ".png");
                if (!file.exists()) {
                    ImageIO.write(new BufferedImage(182, 5, BufferedImage.TYPE_INT_ARGB), "png", file);
                    created.add(file);
                }
            }
        }
        if (!created.isEmpty()) {
            logger.info("HUD assets exported to " + contents.getPath() + " (" + created.size() + " files) – run /iazip once so ItemsAdder ships them.");
        }
        return created;
    }

    private static List<File> writeBox(File file, int width, boolean roundLeft, boolean roundRight) throws IOException {
        if (file.exists()) {
            return List.of();
        }
        BufferedImage image = new BufferedImage(width, BOX_HEIGHT, BufferedImage.TYPE_INT_ARGB);
        int fill = (200 << 24); // black, alpha 200
        for (int y = 0; y < BOX_HEIGHT; y++) {
            for (int x = 0; x < width; x++) {
                boolean corner = false;
                if (roundLeft && x < 3) {
                    corner = (y < 3 - x) || (y >= BOX_HEIGHT - (3 - x));
                }
                if (roundRight && x >= width - 3) {
                    int fromEdge = width - 1 - x;
                    corner = (y < 3 - fromEdge) || (y >= BOX_HEIGHT - (3 - fromEdge));
                }
                image.setRGB(x, y, corner ? 0 : fill);
            }
        }
        ImageIO.write(image, "png", file);
        return List.of(file);
    }
}
